name: Deploy Dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::528555979765:role/GitHubDeployRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Compilar el JAR con Maven
      - name: Build Lambda jar
        run: mvn clean package -f lambda-java/company/pom.xml

      # 3. Mover el JAR generado a la carpeta de Terraform
      - name: Move lambda.jar to Terraform dir
        run: mv lambda-java/company/target/lambdas-1.0-SNAPSHOT.jar infra/dev/functions/company/lambdas-1.0-SNAPSHOT.jar

      - name: Terraform Init
        run: terraform init
        working-directory: infra/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/dev
