name: CI-CD

on:
  permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ID_CUENTA>:role/GitHubDeployRole
          role-session-name: deploySession
          aws-region: us-east-1








